natura-cosmeticos/natds-android

app/src/main/AndroidManifest.xml
build.gradle
designsystem/build.gradle
designsystem/lint-baseline.xml
tools/ktlint.gradle
tools/pipeline_build.sh
tools/publish.gradle

Configure lint and ktlint in the project

[DSY-261] - Config Lint in Project

---

.travis.yml
README.md
app/build.gradle
build.gradle
designsystem/build.gradle
designsystem/src/androidTest/AndroidManifest.xml
designsystem/src/androidTest/kotlin/com/natura/android/ScreenShotTestRunner.kt
designsystem/src/main/AndroidManifest.xml
tools/pipeline_build.sh

Adding screenshot tests library and changing CI build

Adding screenshot tests library and changing CI build

---

build.gradle
designsystem/build.gradle
designsystem/src/main/kotlin/com/natura/android/menu/MenuView.kt
designsystem/src/main/kotlin/com/natura/android/menu/SubMenuView.kt
designsystem/src/main/kotlin/com/natura/android/navigationview/ExpandableNavigationView.kt
designsystem/src/main/res/layout/ds_expandable_navigation_view.xml
designsystem/src/main/res/layout/ds_menu_item.xml
designsystem/src/main/res/layout/ds_menu_view.xml
designsystem/src/main/res/layout/ds_submenu_item.xml
designsystem/src/main/res/layout/ds_submenu_view.xml
gradle.properties
sample/build.gradle
sample/src/androidTest/kotlin/com/natura/android/sample/test/menu/MenuActivityTest.kt
sample/src/main/kotlin/com/natura/android/sample/MainActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/ExpandableNavigationViewActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/MenuActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/SubmenuActivity.kt
sample/src/main/res/layout/activity_expandable_navigation_view.xml
sample/src/main/res/layout/activity_main.xml
sample/src/main/res/layout/component_menu_disable.xml
sample/src/main/res/layout/component_menu_enable.xml
sample/src/main/res/layout/component_menu_opened.xml
sample/src/main/res/layout/component_menu_selected.xml
sample/src/main/res/layout/component_submenu_disable.xml
sample/src/main/res/layout/component_submenu_enable.xml
sample/src/main/res/layout/component_submenu_selected.xml
tools/publish.gradle

Removes androidx library to make components compatible with Natura app.

Remove androidx

---

tools/pipeline_build.sh
tools/publish.gradle

- Enabling package publishing.
- Removing task in CI because of an instability in Travis emulator.
- Changing version number to be published.

Fix build and enable publishing

---

designsystem/src/main/kotlin/com/natura/android/navigationview/ExpandableNavigationView.kt
tools/publish.gradle

Fix behavior when loading data to expandable menu, when there was a non initialized property.

Fix behavior when loading data to expandable menu

---

designsystem/src/main/kotlin/com/natura/android/icon/FontIcon.kt
designsystem/src/main/kotlin/com/natura/android/menu/MenuView.kt
designsystem/src/main/res/layout/ds_menu_view.xml
sample/src/main/kotlin/com/natura/android/sample/components/ExpandableNavigationViewActivity.kt
tools/publish.gradle

Icon Aligment on the left when is empty

---

designsystem/src/main/kotlin/com/natura/android/widget/ValueTextHighlight.kt
designsystem/src/main/res/color/ds_mtrl_colored_stroke_color_selector.xml
designsystem/src/main/res/color/ds_mtrl_default_btn_text_color_selector.xml
designsystem/src/main/res/color/ds_mtrl_sec_btn_background_selector.xml
designsystem/src/main/res/color/ds_mtrl_sec_btn_text_color_selector.xml
designsystem/src/main/res/color/ds_mtrl_sec_colored_btn_text_color_selector.xml
designsystem/src/main/res/color/ds_mtrl_sec_colored_ripple_color_selector.xml
designsystem/src/main/res/values/button_styles.xml
designsystem/src/main/res/values/custom_theme_attrs.xml
designsystem/src/main/res/values/themes.xml
sample/src/androidTest/kotlin/com/natura/android/sample/components/ValueTextHighlightActivityTest.kt
sample/src/main/AndroidManifest.xml
sample/src/main/kotlin/com/natura/android/sample/MainActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/StyleButtonActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/ValueTextHighlightActivity.kt
sample/src/main/res/layout/activity_main.xml
sample/src/main/res/layout/activity_styled_button.xml
sample/src/main/res/layout/activity_text_input_highlight.xml

Added on this pull request:
- Renaming TextInputHighlight component with ValueTextHighlight
- Creating three entry points for button style, **materialButtonStyle**, **materialButtonOutlinedStyle** and **materialBorderlessButtonStyle**
Usage of button style:
`
<Button
...
style="?materialButtonStyle"
.../>
`
as discussed with Lucas Rocha

Minor theme fixes

---

designsystem/src/main/kotlin/com/natura/android/textfield/TextField.kt
designsystem/src/test/kotlin/com/natura/android/textfield/TextFieldTest.kt
sample/src/main/kotlin/com/natura/android/sample/components/TextFieldActivity.kt
sample/src/main/res/layout/activity_textfield.xml

- correct border color for filled text field
- make editText visible
- rename TextFieldInput to TextField, as documentation

[NFS-408] correct filled status and rename class

---

designsystem/src/main/res/values/themes.xml

Fix transparent background issue

---

sample/src/androidTest/kotlin/com/natura/android/sample/MainActivityFunctionalTests.kt
sample/src/main/kotlin/com/natura/android/sample/MainActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/IconActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/LoadingActivity.kt

Adding some functional tests to check how PR workflow at Bitrise behavior

Refactor tests

---

designsystem/src/main/res/values/dimens.xml
designsystem/src/main/res/values/ds_base_attrs.xml
designsystem/src/main/res/values/ds_base_themes.xml
sample/src/main/res/layout/activity_opacity.xml
sample/src/test/kotlin/com/natura/android/sample/tokens/OpacityActivityTest.kt

Adjusting opacity labels and its visualization at sample app

[DSY-000] Adjusting opacity labels and view at sample app

---

designsystem/src/main/res/values/styles.xml
sample/src/main/res/layout/activity_typography.xml
sample/src/test/kotlin/com/natura/android/sample/tokens/TypographyActivityTest.kt
tools/publish.gradle

Set default color to typography as `highMedium`

[DSY-1079] Adjusting typography default color

---

designsystem/src/main/res/color/ds_button_ripple_color.xml
designsystem/src/main/res/values/button_styles.xml
designsystem/src/main/res/values/ds_base_themes.xml

Fixing ripple color to buttons in all brands

[DSY-413] Ajusting ripple color when tap at button

---

sample/src/androidTest/kotlin/com/natura/android/sample/test/AppBarActivityTest.kt
sample/src/androidTest/kotlin/com/natura/android/sample/test/ButtonActivityScreenshotTest.kt
sample/src/androidTest/kotlin/com/natura/android/sample/test/SelectionControlActivityTest.kt

removing tests that are not being executed at pipeline for now, to
enable run instrumentations tests at API 21
- [ X CI Process

[DSY-1218] Ignoring screehshot tests

---

sample/src/androidTest/kotlin/com/natura/android/sample/components/ExpansionPanelActivityTest.kt
sample/src/main/kotlin/com/natura/android/sample/components/ExpansionPanelActivity.kt

Sample app matches component requisites
Ajusting sample app behavior

[DSY-1229] feat: ajusting sample app

---

Makefile
doc/badge.md
tools/screenshot-tools.sh

docs: [DSY-000] Refactor badge doc

---

doc/how-to-contribute.md

Add snapshot version process in how-to-contribute doc

---

build.gradle
doc/typography-token.md

DSY-1331 - Add explanation about bold style at typography-token doc

---

designsystem/src/main/res/values-v21/themes.xml
designsystem/src/main/res/values/ds_base_attrs.xml
designsystem/src/main/res/values/ds_base_themes.xml
designsystem/src/main/res/values/styles.xml
designsystem/src/main/res/values/styles_avon.xml
designsystem/src/main/res/values/styles_natura.xml
designsystem/src/main/res/values/styles_tbs.xml
designsystem/src/main/res/values/themes.xml
doc/typography-token.md

[DSY-1199] - Button default size

---

sample/src/main/res/layout/activity_button.xml
sample/src/main/res/layout/activity_textfield.xml

… textfield label with two lines

Add buttons with different sizes and textfield label with 2 lines in sampleapp

---

designsystem/src/main/res/values/styles.xml

Adjusting default button height

[DSY-1663] Adjusting default button height

---

designsystem/src/main/res/values/styles.xml
doc/button.md
doc/buttonsAvon.png
doc/buttonsNatura.png
doc/buttonsTbs.png
doc/getting-started.md
sample/src/androidTest/kotlin/com/natura/android/sample/components/DialogActivityFunctionalTest.kt
sample/src/main/res/layout/activity_button.xml

Adjusting button height to all android api versions

[DSY1663] Fixing button heignt to all versions

---

designsystem/src/main/kotlin/com/natura/android/card/Card.kt
designsystem/src/main/kotlin/com/natura/android/progressindicator/ProgressIndicator.kt
designsystem/src/main/res/drawable/progress_indicator_layer.xml
designsystem/src/main/res/values-v23/theme_aesop_dark.xml
designsystem/src/main/res/values-v23/theme_aesop_light.xml
designsystem/src/main/res/values-v23/theme_avon_dark.xml
designsystem/src/main/res/values-v23/theme_avon_light.xml
designsystem/src/main/res/values-v23/theme_natura_dark.xml
designsystem/src/main/res/values-v23/theme_natura_light.xml
designsystem/src/main/res/values-v23/theme_the_body_shop_dark.xml
designsystem/src/main/res/values-v23/theme_the_body_shop_light.xml
designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/main/res/values/ds_base_attrs.xml
designsystem/src/main/res/values/ds_base_themes.xml
designsystem/src/main/res/values/styles.xml
designsystem/src/main/res/values/theme_aesop_dark.xml
designsystem/src/main/res/values/theme_aesop_light.xml
designsystem/src/main/res/values/theme_avon_dark.xml
designsystem/src/main/res/values/theme_avon_light.xml
designsystem/src/main/res/values/theme_natura_dark.xml
designsystem/src/main/res/values/theme_natura_light.xml
designsystem/src/main/res/values/theme_the_body_shop_dark.xml
designsystem/src/main/res/values/theme_the_body_shop_light.xml
designsystem/src/test/kotlin/com/natura/android/progressindicator/ProgressIndicatorFixture.kt
designsystem/src/test/kotlin/com/natura/android/progressindicator/ProgressIndicatorTest.kt
doc/getting-started.md
doc/progress-indicator.md
sample/src/main/res/layout/activity_card.xml
sample/src/main/res/layout/activity_progress_indicator.xml

Updates the progress indicator component, inserting size and layer parameters.

[DSY-1898] - Progress indicator update

---

designsystem/src/main/kotlin/com/natura/android/listitem/ListItem.kt
designsystem/src/main/res/color/list_item_color_background_selected.xml
designsystem/src/main/res/drawable/list_item_ripple_background.xml
designsystem/src/main/res/layout/list_item.xml
designsystem/src/main/res/layout/list_item_dividers.xml
designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/test/kotlin/com/natura/android/listitem/ListItemFixture.kt
designsystem/src/test/kotlin/com/natura/android/listitem/ListItemTest.kt
doc/getting-started.md
doc/list-item.md
doc/list-item.png
sample/src/main/AndroidManifest.xml
sample/src/main/kotlin/com/natura/android/sample/MainActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/listitem/ListItemActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/listitem/ListItemAdapter.kt
sample/src/main/res/layout/activity_list_item.xml
sample/src/main/res/layout/activity_main.xml
sample/src/main/res/layout/item_list.xml

Adds List item view, a container that can be applied to the layout of an item in a list.

[DSY-418] - List Item component

---

.cicd/build.sh

…kins Pipeline for Pull requests
Refactor build script to avoid upload artefact error at Jenkins

[FIX]: Refactor build script to avoid upload artefact error at Jenkins

---

designsystem/src/main/kotlin/com/natura/android/menu/MenuView.kt
designsystem/src/main/kotlin/com/natura/android/menu/SubMenuView.kt
designsystem/src/main/kotlin/com/natura/android/navigationview/ExpandableNavigationAdapter.kt
designsystem/src/main/kotlin/com/natura/android/navigationview/Navigation.kt
designsystem/src/main/res/drawable/navigation_item_lowemphasis_background.xml
designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/test/kotlin/com/natura/android/menu/MenuViewTest.kt
sample/src/main/kotlin/com/natura/android/sample/components/ExpandableNavigationViewActivity.kt
sample/src/main/res/layout/activity_expandable_navigation_view.xml
sample/src/main/res/layout/activity_menu.xml
sample/src/main/res/layout/component_menu_lowemphasis.xml

Adds new attribute at MenuView and NavigationItem to allow choice disable appearance but clickable.

[DSY-2245] - Adds Menu item - Low Emphasis

---

build.gradle
designsystem/build.gradle
gradle/wrapper/gradle-wrapper.properties
sample/build.gradle
sample/src/test/resources/robolectric.properties

- Update gradle version to 7.0.0

[DSY-2383]-  Updates gradle to version 7.0.0

---

build.gradle
designsystem/build.gradle
designsystem/src/main/kotlin/com/natura/android/progressindicator/ProgressIndicator.kt
designsystem/src/main/kotlin/com/natura/android/shortcut/Shortcut.kt
designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/main/res/values/styles.xml
designsystem/src/test/kotlin/com/natura/android/progressindicator/ProgressIndicatorFixture.kt
designsystem/src/test/kotlin/com/natura/android/shortcut/ShortcutFixture.kt
doc/progress-indicator.md
doc/shortcut.md
gradle.properties
gradle/wrapper/gradle-wrapper.properties
sample/build.gradle
sample/src/main/res/layout/activity_progress_indicator.xml
sample/src/main/res/layout/activity_shortcut.xml

⚠️⚠️⚠️ BREAKING CHANGE: The previous version of the component is no longer compatible as attributes have been refactored. ⚠️⚠️⚠️  
Adds prefixes in shorctut and progress indicator attributes to avoid conflicts with other libs
Progress Indicator:
customHeight -> pgid_height
customWidth -> pgid_width
layer -> pgid_layer
size -> pgid_size
Shortcut:
colorIcon -> shct_icon_color
textLabel -> shct_text_label
iconName -> shct_icon_name
notify -> shct_notify

[DSY-2421] - Adds prefixes in shorctut and progress indicator attributes to avoid conflicts with other libs

---

designsystem/src/main/kotlin/com/natura/android/tag/Tag.kt
designsystem/src/main/res/drawable/tag_background.xml
designsystem/src/main/res/layout/ds_tag.xml
designsystem/src/main/res/values-v23/theme_aesop_dark.xml
designsystem/src/main/res/values-v23/theme_aesop_light.xml
designsystem/src/main/res/values-v23/theme_avon_dark.xml
designsystem/src/main/res/values-v23/theme_avon_light.xml
designsystem/src/main/res/values-v23/theme_natura_dark.xml
designsystem/src/main/res/values-v23/theme_natura_light.xml
designsystem/src/main/res/values-v23/theme_the_body_shop_dark.xml
designsystem/src/main/res/values-v23/theme_the_body_shop_light.xml
designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/main/res/values/styles.xml
designsystem/src/main/res/values/theme_aesop_dark.xml
designsystem/src/main/res/values/theme_aesop_light.xml
designsystem/src/main/res/values/theme_attributes.xml
designsystem/src/main/res/values/theme_avon_dark.xml
designsystem/src/main/res/values/theme_avon_light.xml
designsystem/src/main/res/values/theme_natura_dark.xml
designsystem/src/main/res/values/theme_natura_light.xml
designsystem/src/main/res/values/theme_the_body_shop_dark.xml
designsystem/src/main/res/values/theme_the_body_shop_light.xml

- Update tag typography tokens to make it customizable

[DSY-2312] - Update tag typography

---

designsystem/src/main/kotlin/com/natura/android/radiobutton/RadioButton.kt
designsystem/src/main/res/values/ds_base_attrs.xml
designsystem/src/main/res/values/styles.xml
designsystem/src/main/res/values/styles_aesop.xml
designsystem/src/main/res/values/styles_avon.xml
designsystem/src/main/res/values/styles_natura.xml
designsystem/src/main/res/values/styles_tbs.xml
doc/radiobutton.md
sample/src/main/res/layout/activity_radiobutton.xml

Transform the Radio Button style into a Design System component, providing openness to other functionalities and customizations

[DSY-2311 / DSY-2444] Adds RadioButton Component from its style and applies typography

---

designsystem/src/main/res/values/ds_attrs.xml
designsystem/src/main/res/values/ds_base_attrs.xml
designsystem/src/main/res/values/styles.xml

- Update Shortcut typography tokens to make it customizable

[DSY-2313] - Update Shorcut typography

---

designsystem/src/main/kotlin/com/natura/android/appbartop/StandardAppBarTop.kt
designsystem/src/main/res/values/styles.xml

- Update AppBarTop typography tokens to make it customizable

[DSY-2314] - Update AppBar Top typography

---

designsystem/src/main/kotlin/com/natura/android/widget/ValueTextHighlight.kt
sample/src/androidTest/kotlin/com/natura/android/sample/MainActivityFunctionalTests.kt
sample/src/main/res/layout/activity_main.xml

- Deprecates ValueTextHighLight component, which will no longer receive updates and fixes.

[DSY-2410] - Deprecates ValueTextHighLight component

---

tools/bump_version.sh

chore: update bump_version

---

designsystem/src/main/kotlin/com/natura/android/avatar/Avatar.kt
designsystem/src/main/kotlin/com/natura/android/badge/BadgeDrawable.kt
designsystem/src/main/kotlin/com/natura/android/checkbox/CheckBox.kt
designsystem/src/main/kotlin/com/natura/android/iconButton/IconButton.kt
designsystem/src/main/kotlin/com/natura/android/listitem/ListItem.kt
designsystem/src/main/kotlin/com/natura/android/logo/Logo.kt
designsystem/src/main/kotlin/com/natura/android/progressindicator/ProgressIndicator.kt
designsystem/src/main/kotlin/com/natura/android/shortcut/Shortcut.kt
designsystem/src/main/kotlin/com/natura/android/tag/Tag.kt
designsystem/src/main/kotlin/com/natura/android/textfield/TextField.kt
designsystem/src/main/res/layout/ds_expandable_navigation_view.xml
designsystem/src/main/res/layout/ds_expansion_panel.xml
sample/src/main/kotlin/com/natura/android/sample/components/AppBarTopActivity.kt
sample/src/main/kotlin/com/natura/android/sample/components/DialogActivity.kt
sample/src/main/res/layout/appbartop_button_action.xml
sample/src/main/res/layout/appbartop_search.xml
sample/src/main/res/layout/appbartop_threeactions.xml
sample/src/main/res/layout/appbartop_title_center.xml
sample/src/main/res/layout/appbartop_title_long.xml
sample/src/main/res/layout/appbartop_twoactions.xml
tools/create_docs.sh
tools/finish_emulators.sh
tools/pipeline_build.sh
tools/update_icons.sh

- Fixes code bugs and warnings generated from Android Studio.

[DSY-2540] - Fixes code bugs and warnings generated from Android Studio.

---

Makefile
designsystem/src/main/kotlin/com/natura/android/dialog/DialogAlert.kt
designsystem/src/main/kotlin/com/natura/android/dialog/DialogStandard.kt
designsystem/src/main/res/values/styles.xml
designsystem/src/main/res/values/styles_aesop.xml
designsystem/src/main/res/values/styles_avon.xml
designsystem/src/main/res/values/styles_natura.xml
designsystem/src/main/res/values/styles_tbs.xml

- Updates Dialog component with border radius attribute, customized by theme.

Adds Custom Border Radius to Dialog component

---

.github/release-drafter.yml

- Adds Release Drafter plugin to generate release notes automatically

[DSY-2183] - Adds Release Drafter plugin to generate release notes automatically

---

.github/release-drafter.yml

- Adds Release Drafter plugin to generate release notes automatically

Adds Release Drafter plugin to generate release notes automatically

---

build.gradle
designsystem/build.gradle
jacoco/modules.gradle
jacoco/project.gradle
sample/build.gradle

- Adds Jacoco tool to get tests coverage

[DSY-2180] - Adds Jacoco tool to get tests coverage

---

Makefile
designsystem/src/main/res/values/theme_consultoria_de_beleza_dark_ssot.xml
designsystem/src/main/res/values/theme_consultoria_de_beleza_light_ssot.xml
sample/src/main/kotlin/com/natura/android/sample/MainActivity.kt
sample/src/test/kotlin/com/natura/android/sample/tokens/ColorsActivityNaturaTest.kt

fix: build fix

---

designsystem/src/main/res/color/button_contained_background_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_contained_background_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/button_contained_label_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_contained_label_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/button_contained_stroke_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_contained_stroke_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/button_outlined_background_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_outlined_background_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/button_outlined_label_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_outlined_label_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/button_outlined_stroke_color_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/button_outlined_stroke_color_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/color_checkbox_primary_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/color_checkbox_primary_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/color_selector_primary_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/color_selector_primary_consultoria_de_beleza_light.xml
designsystem/src/main/res/color/color_selector_secondary_consultoria_de_beleza_dark.xml
designsystem/src/main/res/color/color_selector_secondary_consultoria_de_beleza_light.xml
designsystem/src/main/res/values-v23/theme_consultoria_de_beleza_dark.xml
designsystem/src/main/res/values-v23/theme_consultoria_de_beleza_light.xml
designsystem/src/main/res/values/styles_consultoria_de_beleza.xml
designsystem/src/main/res/values/theme_consultoria_de_beleza_dark.xml

Adds style and custom attributes to Consultoria de Beleza theme. The miss of these files was impacting the correct visualization of the theme in components and styles created within the Design System. impacting the correct visualization of the theme in components and styles created within the Design System.

[JGPM-68] - Adds style and custom attributes to Consultoria de Beleza theme

---

Makefile
designsystem/build.gradle

lint test for pipe

---

Makefile
designsystem/build.gradle

lint test removing

---

designsystem/src/test/kotlin/com/natura/android/dialog/DialogStandardTest.kt

fix unit tests

---

sample/build.gradle
sample/src/androidTest/kotlin/com/natura/android/sample/MainActivityFunctionalTests.kt

sample lint fix

---

designsystem/src/main/kotlin/com/natura/android/appbartop/StandardAppBarTop.kt

fix standart appbar

---

designsystem/src/main/kotlin/com/natura/android/appbartop/StandardAppBarTop.kt
designsystem/src/test/kotlin/com/natura/android/appbartop/StandardAppBarTopTest.kt

fix unit tests related to getColor func on AppBarStandard

---

designsystem/src/test/kotlin/com/natura/android/button/ContainedButtonTest.kt

unit tests of containerButton

---

designsystem/src/main/kotlin/com/natura/android/textfield/TextField.kt

fixing textfield klint errors

---

designsystem/src/main/res/layout/snackbar.xml
sample/src/main/kotlin/com/natura/android/sample/components/SnackbarActivity.kt

fix snackbar icon

---

designsystem/src/main/kotlin/com/natura/android/select/Select.kt

Fix for crashlytics crash in select component

fix cast error for select component
